<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.7.6" />
    <PackageReference Include="Blazorise.Charts" Version="1.7.6" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.7.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.15" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0" />
  </ItemGroup>

</Project>
